pagina_votos/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include("polls.urls"), name='polls')
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    #ex: /polls/
    path("", views.IndexView.as_view(), name='index'),
    #ex: /polls/3/
    path("<int:pk>/", views.DetailView.as_view(), name='details'),
    #ex: /polls/4/results/
    path("<int:pk>/results/", views.ResultView.as_view(), name='results'),
    #ex: /polls/6/votes
    path("<int:question_id>/vote/", views.vote, name='votes')
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Question(models.Model):

    question_text = models.CharField(max_length=200)
    
    pub_date = models.DateTimeField("date_published",default=timezone.now)
    
    def __str__(self):
        return f"{self.id}: {self.question_text}"
    
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    choice_text = models.CharField(max_length=200)

    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# def index(request):
#     lastest_question_list = Question.objects.all()
#     return render(request,"polls/index.html",{
#         'lastest_question_list': lastest_question_list
#     })


# def detail(request, question_id):
    
#     question = get_object_or_404(Question, id = question_id)
#     return render(request, "polls/detail.html", {
#         'question': question
#     })


# def results(request, question_id):
#     question = get_object_or_404(Question, id = question_id)
#     return render(request, 'polls/results.html', {
#         'question': question
#     })


class IndexView(generic.ListView):
    
    template_name = "polls/index.html"
    context_object_name = "lastest_question_list"
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question    
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """Exclude any question that aren't published yet"""
        
        return Question.objects.filter(pub_date__lte=timezone.now())    


class ResultView(generic.DetailView):
    model = Question    
    template_name = 'polls/results.html'
    
    def get_queryset(self):
        """Exclude any question that aren't published yet"""
        
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    
    question = get_object_or_404(Question, id = question_id)
    try:
        selected_choice = question.choice_set.get(id = request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            "error_message": 'no elegiste una respuesta'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        

polls/templates/polls/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="{% static 'polls/detail.css' %}">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'polls:votes' question.id %}" method='post'>
        {% csrf_token %}
        
        <fieldset>
            <legend><h1>{{question.question_text}}</h1></legend>
            {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input 
                    type="radio"
                    name='choice'
                    id='choice{{forloop.counter}}'
                    value='{{choice.id}}'
                >
                <label for="choice {{forloop.counter}}">
                    {{choice.choice_text}}
                </label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value='Votar' id="boton">
        </form>
</body>
</html>








{% comment %} 

<h1>{{question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{choice.choice_text}}
    </li>
    {% endfor %}
</ul> 

{% endcomment %}

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/reset.css' %}">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Premios PlatziApp</title>
</head>
<body>

    <header>
        <h1>Premios PlatziApp</h1>
    </header>

    <main>
        {% if lastest_question_list %}
            <ul>
                {% for question in lastest_question_list %}
                    <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No Polls are available.</p>
        {% endif %}
    </main>

    <footer>
        <a href="https://platzi.com">Platzi</a>
        <a href="#">Contacto</a>
        <a href="#">¿Quieres ser profe?</a>
        <a href="#">Políticas de privacidad</a>
        <a href="#">Términos y condiciones</a>
    </footer>

</body>
</html>




{% comment %} {% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if lastest_question_list %}
    <ul>
        {% for question in lastest_question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Polls are available.</p>
{% endif %} {% endcomment %}

polls/templates/polls/results.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="{% static 'polls/detail.css' %}">
    <title>Resultados: {{question.question_text}}</title>
</head>

<body>
    <form> <!-- * i added this to correct an error of the h1 visualization 😅 */ -->
    <fieldset>
        <legend><h1>Resultados: {{ question.question_text }}</h1></legend>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}: {{ choice.votes }} vote{{ choice.votes|pluralize}} </li>
        {% endfor %}
        </ul>
    <fieldset>
    </form>
    <buttonid="boton"><a href="{% url 'polls:details' question.id %}">¿Te gustaría votar de nuevo?</a></buttonid=>
</body>